import { NextResponse } from "next/server";
import { db } from "@/lib/db";
import { auth } from "@/lib/auth";

// Greater Accra and Tema Healthcare Facilities
const FACILITIES = [
  // Hospitals in Greater Accra
  {
    name: "Korle Bu Teaching Hospital",
    slug: "korle-bu-teaching-hospital",
    type: "HOSPITAL",
    phone: "0302665401",
    email: "info@kfrh.gov.gh",
    address: "Guggisberg Avenue",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.5344,
    longitude: -0.2251,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 2000,
    icuBedsAvailable: 50,
    description: "Ghana's premier teaching hospital and the third largest hospital in Africa.",
  },
  {
    name: "37 Military Hospital",
    slug: "37-military-hospital",
    type: "HOSPITAL",
    phone: "0302776111",
    email: "info@37milhosp.gov.gh",
    address: "Liberation Road",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.5797,
    longitude: -0.1849,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 600,
    icuBedsAvailable: 30,
    description: "A military hospital that also serves civilians. Known for excellent trauma care.",
  },
  {
    name: "Ridge Hospital",
    slug: "ridge-hospital",
    type: "HOSPITAL",
    phone: "0302228315",
    email: "info@ridgehospital.gov.gh",
    address: "Castle Road, Ridge",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.5628,
    longitude: -0.1969,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 420,
    icuBedsAvailable: 20,
    description: "A major government hospital in the heart of Accra.",
  },
  {
    name: "Tema General Hospital",
    slug: "tema-general-hospital",
    type: "HOSPITAL",
    phone: "0303212222",
    email: "info@temageneralhospital.gov.gh",
    address: "Hospital Road, Community 1",
    city: "Tema",
    districtName: "Tema Metropolitan",
    latitude: 5.6698,
    longitude: -0.0166,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 350,
    icuBedsAvailable: 15,
    description: "The main government hospital serving Tema and surrounding communities.",
  },
  {
    name: "Lekma Hospital",
    slug: "lekma-hospital",
    type: "HOSPITAL",
    phone: "0302813456",
    email: "info@lekmahospital.gov.gh",
    address: "Teshie-Nungua",
    city: "Accra",
    districtName: "Ledzokuku-Krowor",
    latitude: 5.5922,
    longitude: -0.0975,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 200,
    icuBedsAvailable: 10,
    description: "A district hospital serving the Ledzokuku-Krowor Municipality.",
  },
  {
    name: "Nyaho Medical Centre",
    slug: "nyaho-medical-centre",
    type: "HOSPITAL",
    phone: "0302775341",
    email: "info@nyahomedical.com",
    address: "7th Avenue, Ridge",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.5612,
    longitude: -0.1891,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 80,
    icuBedsAvailable: 8,
    description: "A leading private hospital offering world-class healthcare services.",
  },
  {
    name: "Trust Hospital Osu",
    slug: "trust-hospital-osu",
    type: "HOSPITAL",
    phone: "0302761974",
    email: "info@trusthospitals.com",
    address: "Osu, Oxford Street",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.5571,
    longitude: -0.1818,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 60,
    icuBedsAvailable: 6,
    description: "A trusted private hospital chain with multiple locations across Accra.",
  },
  // Polyclinics
  {
    name: "Mamprobi Polyclinic",
    slug: "mamprobi-polyclinic",
    type: "POLYCLINIC",
    phone: "0302223456",
    email: "mamprobi.polyclinic@ghs.gov.gh",
    address: "Mamprobi",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.5389,
    longitude: -0.2356,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: false,
    bedCount: 40,
    icuBedsAvailable: 0,
    description: "A government polyclinic providing primary healthcare services.",
  },
  {
    name: "Tema Polyclinic",
    slug: "tema-polyclinic",
    type: "POLYCLINIC",
    phone: "0303215678",
    email: "tema.polyclinic@ghs.gov.gh",
    address: "Community 2",
    city: "Tema",
    districtName: "Tema Metropolitan",
    latitude: 5.6712,
    longitude: -0.0234,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: false,
    bedCount: 35,
    icuBedsAvailable: 0,
    description: "A government polyclinic serving the Tema community.",
  },
  {
    name: "La General Hospital",
    slug: "la-general-hospital",
    type: "POLYCLINIC",
    phone: "0302772345",
    email: "la.general@ghs.gov.gh",
    address: "La, Trade Fair",
    city: "Accra",
    districtName: "La Dade-Kotopon",
    latitude: 5.5756,
    longitude: -0.1567,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 100,
    icuBedsAvailable: 5,
    description: "A major polyclinic serving the La community.",
  },
  {
    name: "Ashaiman Polyclinic",
    slug: "ashaiman-polyclinic",
    type: "POLYCLINIC",
    phone: "0303305678",
    email: "ashaiman.polyclinic@ghs.gov.gh",
    address: "Ashaiman",
    city: "Ashaiman",
    districtName: "Ashaiman Municipal",
    latitude: 5.6912,
    longitude: -0.0345,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 50,
    icuBedsAvailable: 2,
    description: "The main government health facility serving Ashaiman Municipality.",
  },
  // Clinics
  {
    name: "Tema Community 5 Clinic",
    slug: "tema-community-5-clinic",
    type: "CLINIC",
    phone: "0303218901",
    email: "c5clinic@ghs.gov.gh",
    address: "Community 5",
    city: "Tema",
    districtName: "Tema Metropolitan",
    latitude: 5.6634,
    longitude: -0.0089,
    nhisAccredited: true,
    emergencyCapable: false,
    ambulanceAvailable: false,
    bedCount: 10,
    icuBedsAvailable: 0,
    description: "A community clinic providing basic healthcare services.",
  },
  {
    name: "Bethel Clinic Tema",
    slug: "bethel-clinic-tema",
    type: "CLINIC",
    phone: "0303219876",
    email: "info@bethelclinic.com",
    address: "Community 11",
    city: "Tema",
    districtName: "Tema Metropolitan",
    latitude: 5.6589,
    longitude: 0.0012,
    nhisAccredited: true,
    emergencyCapable: false,
    ambulanceAvailable: false,
    bedCount: 15,
    icuBedsAvailable: 0,
    description: "A private clinic offering quality healthcare services.",
  },
  // Health Centres
  {
    name: "Sakumono Health Centre",
    slug: "sakumono-health-centre",
    type: "HEALTH_CENTRE",
    phone: "0303456789",
    email: "sakumono.hc@ghs.gov.gh",
    address: "Sakumono Estate",
    city: "Tema",
    districtName: "Tema Metropolitan",
    latitude: 5.6234,
    longitude: -0.0456,
    nhisAccredited: true,
    emergencyCapable: false,
    ambulanceAvailable: false,
    bedCount: 8,
    icuBedsAvailable: 0,
    description: "A health centre providing primary healthcare to Sakumono residents.",
  },
  {
    name: "Lashibi Health Centre",
    slug: "lashibi-health-centre",
    type: "HEALTH_CENTRE",
    phone: "0303467890",
    email: "lashibi.hc@ghs.gov.gh",
    address: "Lashibi",
    city: "Tema",
    districtName: "Tema Metropolitan",
    latitude: 5.6345,
    longitude: -0.0567,
    nhisAccredited: true,
    emergencyCapable: false,
    ambulanceAvailable: false,
    bedCount: 6,
    icuBedsAvailable: 0,
    description: "A community health centre serving the Lashibi area.",
  },
  // Pharmacies
  {
    name: "Ernest Chemist Tema",
    slug: "ernest-chemist-tema",
    type: "PHARMACY",
    phone: "0303220123",
    email: "tema@ernestchemist.com",
    address: "Community 1, Main Road",
    city: "Tema",
    districtName: "Tema Metropolitan",
    latitude: 5.6701,
    longitude: -0.0178,
    nhisAccredited: false,
    emergencyCapable: false,
    ambulanceAvailable: false,
    bedCount: 0,
    icuBedsAvailable: 0,
    description: "A leading pharmacy chain providing quality medicines.",
  },
  {
    name: "Kama Pharmacy 24hr",
    slug: "kama-pharmacy-accra",
    type: "PHARMACY",
    phone: "0302789012",
    email: "info@kamapharmacy.com",
    address: "Osu, Cantonments",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.5612,
    longitude: -0.1756,
    nhisAccredited: false,
    emergencyCapable: false,
    ambulanceAvailable: false,
    bedCount: 0,
    icuBedsAvailable: 0,
    description: "A 24-hour pharmacy providing medicines and pharmaceutical services.",
  },
  // Diagnostic Centres
  {
    name: "Medlab Ghana Tema",
    slug: "medlab-ghana-tema",
    type: "DIAGNOSTIC_CENTRE",
    phone: "0303221234",
    email: "tema@medlabghana.com",
    address: "Community 2",
    city: "Tema",
    districtName: "Tema Metropolitan",
    latitude: 5.6723,
    longitude: -0.0212,
    nhisAccredited: true,
    emergencyCapable: false,
    ambulanceAvailable: false,
    bedCount: 0,
    icuBedsAvailable: 0,
    description: "A modern diagnostic centre offering laboratory and imaging services.",
  },
  {
    name: "Nyaho Diagnostic Centre",
    slug: "nyaho-diagnostic-centre",
    type: "DIAGNOSTIC_CENTRE",
    phone: "0302775342",
    email: "diagnostics@nyahomedical.com",
    address: "Airport Residential",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.5734,
    longitude: -0.1823,
    nhisAccredited: true,
    emergencyCapable: false,
    ambulanceAvailable: false,
    bedCount: 0,
    icuBedsAvailable: 0,
    description: "State-of-the-art diagnostic facility with advanced imaging services.",
  },
  // Maternity Homes
  {
    name: "Tema Maternity Home",
    slug: "tema-maternity-home",
    type: "MATERNITY_HOME",
    phone: "0303222345",
    email: "temamaternity@ghs.gov.gh",
    address: "Community 3",
    city: "Tema",
    districtName: "Tema Metropolitan",
    latitude: 5.6678,
    longitude: -0.0145,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: false,
    bedCount: 25,
    icuBedsAvailable: 2,
    description: "A specialized maternity facility providing antenatal and delivery care.",
  },
  {
    name: "Marie Stopes Accra",
    slug: "marie-stopes-accra",
    type: "MATERNITY_HOME",
    phone: "0302234567",
    email: "accra@mariestopes.org.gh",
    address: "Asylum Down",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.5567,
    longitude: -0.2123,
    nhisAccredited: true,
    emergencyCapable: false,
    ambulanceAvailable: false,
    bedCount: 15,
    icuBedsAvailable: 0,
    description: "Reproductive health clinic offering family planning and maternal health.",
  },
  // Additional Greater Accra Hospitals
  {
    name: "University of Ghana Medical Centre",
    slug: "university-of-ghana-medical-centre",
    type: "HOSPITAL",
    phone: "0302213850",
    email: "info@ugmc.ug.edu.gh",
    address: "Legon",
    city: "Accra",
    districtName: "Ga East Municipal",
    latitude: 5.6508,
    longitude: -0.1869,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 650,
    icuBedsAvailable: 40,
    description: "A state-of-the-art teaching hospital affiliated with the University of Ghana.",
  },
  {
    name: "Police Hospital",
    slug: "police-hospital-accra",
    type: "HOSPITAL",
    phone: "0302773906",
    email: "info@policehospital.gov.gh",
    address: "Cantonments",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.5678,
    longitude: -0.1734,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 200,
    icuBedsAvailable: 12,
    description: "Ghana Police Service hospital also serving the general public.",
  },
  {
    name: "Achimota Hospital",
    slug: "achimota-hospital",
    type: "HOSPITAL",
    phone: "0302401234",
    email: "info@achimotahospital.gov.gh",
    address: "Achimota",
    city: "Accra",
    districtName: "Ga West Municipal",
    latitude: 5.6156,
    longitude: -0.2289,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 180,
    icuBedsAvailable: 8,
    description: "A district hospital serving Achimota and surrounding communities.",
  },
  {
    name: "Ga South Municipal Hospital",
    slug: "ga-south-municipal-hospital",
    type: "HOSPITAL",
    phone: "0302945678",
    email: "info@gasouthhospital.gov.gh",
    address: "Weija",
    city: "Accra",
    districtName: "Ga South Municipal",
    latitude: 5.5567,
    longitude: -0.3234,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 150,
    icuBedsAvailable: 6,
    description: "Municipal hospital serving the Ga South district.",
  },
  {
    name: "Pantang Hospital",
    slug: "pantang-hospital",
    type: "HOSPITAL",
    phone: "0302506789",
    email: "info@pantanghospital.gov.gh",
    address: "Pantang",
    city: "Accra",
    districtName: "Ga East Municipal",
    latitude: 5.6789,
    longitude: -0.1567,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 500,
    icuBedsAvailable: 10,
    description: "A psychiatric hospital providing mental health services.",
  },
  {
    name: "Amasaman Government Hospital",
    slug: "amasaman-government-hospital",
    type: "HOSPITAL",
    phone: "0302956789",
    email: "info@amasamanhospital.gov.gh",
    address: "Amasaman",
    city: "Accra",
    districtName: "Ga West Municipal",
    latitude: 5.7012,
    longitude: -0.2789,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 120,
    icuBedsAvailable: 5,
    description: "Government hospital serving Ga West Municipality.",
  },
  {
    name: "Legon Hospital",
    slug: "legon-hospital",
    type: "HOSPITAL",
    phone: "0302500381",
    email: "info@legonhospital.ug.edu.gh",
    address: "University of Ghana, Legon",
    city: "Accra",
    districtName: "Ga East Municipal",
    latitude: 5.6478,
    longitude: -0.1856,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 80,
    icuBedsAvailable: 4,
    description: "University hospital serving students and the Legon community.",
  },
  {
    name: "Cocoa Clinic",
    slug: "cocoa-clinic-accra",
    type: "HOSPITAL",
    phone: "0302228888",
    email: "info@cocoaclinic.com",
    address: "Cantonments",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.5712,
    longitude: -0.1678,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 100,
    icuBedsAvailable: 8,
    description: "A well-established private hospital with comprehensive healthcare services.",
  },
  {
    name: "Euracare Advanced Diagnostics & Heart Centre",
    slug: "euracare-heart-centre",
    type: "HOSPITAL",
    phone: "0302739393",
    email: "info@euracareghana.com",
    address: "Airport Residential Area",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.5789,
    longitude: -0.1812,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 50,
    icuBedsAvailable: 10,
    description: "Specialized cardiac care and advanced diagnostic centre.",
  },
  {
    name: "Rabito Clinic",
    slug: "rabito-clinic-accra",
    type: "HOSPITAL",
    phone: "0302784848",
    email: "info@rabitoclinic.com",
    address: "Osu",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.5534,
    longitude: -0.1789,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 40,
    icuBedsAvailable: 4,
    description: "Private hospital known for quality healthcare and fertility services.",
  },
  {
    name: "Medifem Multi-Specialist Hospital",
    slug: "medifem-hospital",
    type: "HOSPITAL",
    phone: "0302817272",
    email: "info@medifemhospital.com",
    address: "East Legon",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.6234,
    longitude: -0.1567,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 60,
    icuBedsAvailable: 6,
    description: "Multi-specialist hospital with focus on women's health and fertility.",
  },
  {
    name: "The Bank Hospital",
    slug: "the-bank-hospital",
    type: "HOSPITAL",
    phone: "0302610300",
    email: "info@thebankhospital.com",
    address: "North Ridge",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.5656,
    longitude: -0.2012,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 70,
    icuBedsAvailable: 8,
    description: "Premium private hospital offering comprehensive medical services.",
  },
  {
    name: "Akai House Clinic",
    slug: "akai-house-clinic",
    type: "HOSPITAL",
    phone: "0302763972",
    email: "info@akaihouseclinic.com",
    address: "Airport Residential",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.5801,
    longitude: -0.1756,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 45,
    icuBedsAvailable: 5,
    description: "Private clinic offering specialized medical care.",
  },
  // Additional Polyclinics
  {
    name: "Kaneshie Polyclinic",
    slug: "kaneshie-polyclinic",
    type: "POLYCLINIC",
    phone: "0302229876",
    email: "kaneshie.polyclinic@ghs.gov.gh",
    address: "Kaneshie",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.5534,
    longitude: -0.2345,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 60,
    icuBedsAvailable: 3,
    description: "Government polyclinic serving the Kaneshie community.",
  },
  {
    name: "Dansoman Polyclinic",
    slug: "dansoman-polyclinic",
    type: "POLYCLINIC",
    phone: "0302311234",
    email: "dansoman.polyclinic@ghs.gov.gh",
    address: "Dansoman",
    city: "Accra",
    districtName: "Ablekuma West Municipal",
    latitude: 5.5312,
    longitude: -0.2567,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 55,
    icuBedsAvailable: 2,
    description: "Government polyclinic serving Dansoman and surrounding areas.",
  },
  {
    name: "Maamobi General Hospital",
    slug: "maamobi-general-hospital",
    type: "POLYCLINIC",
    phone: "0302245678",
    email: "maamobi.hospital@ghs.gov.gh",
    address: "Maamobi",
    city: "Accra",
    districtName: "Ayawaso North Municipal",
    latitude: 5.5789,
    longitude: -0.2123,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 80,
    icuBedsAvailable: 4,
    description: "General hospital serving the Maamobi community.",
  },
  {
    name: "Adabraka Polyclinic",
    slug: "adabraka-polyclinic",
    type: "POLYCLINIC",
    phone: "0302224567",
    email: "adabraka.polyclinic@ghs.gov.gh",
    address: "Adabraka",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.5567,
    longitude: -0.2089,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: false,
    bedCount: 45,
    icuBedsAvailable: 2,
    description: "Government polyclinic in the heart of Adabraka.",
  },
  {
    name: "Madina Polyclinic",
    slug: "madina-polyclinic",
    type: "POLYCLINIC",
    phone: "0302512345",
    email: "madina.polyclinic@ghs.gov.gh",
    address: "Madina",
    city: "Accra",
    districtName: "La Nkwantanang-Madina Municipal",
    latitude: 5.6712,
    longitude: -0.1678,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 70,
    icuBedsAvailable: 3,
    description: "Government polyclinic serving the Madina community.",
  },
  {
    name: "Kpeshie Polyclinic",
    slug: "kpeshie-polyclinic",
    type: "POLYCLINIC",
    phone: "0302713456",
    email: "kpeshie.polyclinic@ghs.gov.gh",
    address: "Kpeshie",
    city: "Accra",
    districtName: "La Dade-Kotopon",
    latitude: 5.5889,
    longitude: -0.1234,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: false,
    bedCount: 40,
    icuBedsAvailable: 2,
    description: "Government polyclinic serving the Kpeshie area.",
  },
  // Additional Clinics
  {
    name: "Spintex Medical Centre",
    slug: "spintex-medical-centre",
    type: "CLINIC",
    phone: "0302812345",
    email: "info@spintexmedical.com",
    address: "Spintex Road",
    city: "Accra",
    districtName: "Ledzokuku-Krowor",
    latitude: 5.6234,
    longitude: -0.0789,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: false,
    bedCount: 25,
    icuBedsAvailable: 2,
    description: "Private medical centre on Spintex Road.",
  },
  {
    name: "East Legon Medical Centre",
    slug: "east-legon-medical-centre",
    type: "CLINIC",
    phone: "0302523456",
    email: "info@eastlegonmedical.com",
    address: "East Legon",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.6345,
    longitude: -0.1456,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: false,
    bedCount: 20,
    icuBedsAvailable: 2,
    description: "Private clinic serving the East Legon community.",
  },
  {
    name: "Lapaz Community Clinic",
    slug: "lapaz-community-clinic",
    type: "CLINIC",
    phone: "0302412345",
    email: "lapaz.clinic@ghs.gov.gh",
    address: "Lapaz",
    city: "Accra",
    districtName: "Ga Central Municipal",
    latitude: 5.6012,
    longitude: -0.2456,
    nhisAccredited: true,
    emergencyCapable: false,
    ambulanceAvailable: false,
    bedCount: 15,
    icuBedsAvailable: 0,
    description: "Community clinic serving Lapaz residents.",
  },
  {
    name: "Teshie Clinic",
    slug: "teshie-clinic",
    type: "CLINIC",
    phone: "0302714567",
    email: "teshie.clinic@ghs.gov.gh",
    address: "Teshie",
    city: "Accra",
    districtName: "Ledzokuku-Krowor",
    latitude: 5.5834,
    longitude: -0.1089,
    nhisAccredited: true,
    emergencyCapable: false,
    ambulanceAvailable: false,
    bedCount: 12,
    icuBedsAvailable: 0,
    description: "Government clinic serving the Teshie community.",
  },
  {
    name: "Nungua Clinic",
    slug: "nungua-clinic",
    type: "CLINIC",
    phone: "0302715678",
    email: "nungua.clinic@ghs.gov.gh",
    address: "Nungua",
    city: "Accra",
    districtName: "Ledzokuku-Krowor",
    latitude: 5.5912,
    longitude: -0.0856,
    nhisAccredited: true,
    emergencyCapable: false,
    ambulanceAvailable: false,
    bedCount: 10,
    icuBedsAvailable: 0,
    description: "Government clinic serving the Nungua community.",
  },
  // Additional Health Centres
  {
    name: "Dome Health Centre",
    slug: "dome-health-centre",
    type: "HEALTH_CENTRE",
    phone: "0302413456",
    email: "dome.hc@ghs.gov.gh",
    address: "Dome",
    city: "Accra",
    districtName: "Ga East Municipal",
    latitude: 5.6456,
    longitude: -0.2234,
    nhisAccredited: true,
    emergencyCapable: false,
    ambulanceAvailable: false,
    bedCount: 10,
    icuBedsAvailable: 0,
    description: "Health centre serving the Dome community.",
  },
  {
    name: "Kwabenya Health Centre",
    slug: "kwabenya-health-centre",
    type: "HEALTH_CENTRE",
    phone: "0302514567",
    email: "kwabenya.hc@ghs.gov.gh",
    address: "Kwabenya",
    city: "Accra",
    districtName: "Ga East Municipal",
    latitude: 5.6789,
    longitude: -0.2012,
    nhisAccredited: true,
    emergencyCapable: false,
    ambulanceAvailable: false,
    bedCount: 8,
    icuBedsAvailable: 0,
    description: "Health centre serving Kwabenya and surrounding areas.",
  },
  {
    name: "Adenta Health Centre",
    slug: "adenta-health-centre",
    type: "HEALTH_CENTRE",
    phone: "0302523456",
    email: "adenta.hc@ghs.gov.gh",
    address: "Adenta",
    city: "Accra",
    districtName: "Adentan Municipal",
    latitude: 5.7012,
    longitude: -0.1567,
    nhisAccredited: true,
    emergencyCapable: false,
    ambulanceAvailable: false,
    bedCount: 12,
    icuBedsAvailable: 0,
    description: "Health centre serving the Adenta community.",
  },
  {
    name: "Kasoa Health Centre",
    slug: "kasoa-health-centre",
    type: "HEALTH_CENTRE",
    phone: "0302934567",
    email: "kasoa.hc@ghs.gov.gh",
    address: "Kasoa",
    city: "Kasoa",
    districtName: "Ga South Municipal",
    latitude: 5.5234,
    longitude: -0.4234,
    nhisAccredited: true,
    emergencyCapable: false,
    ambulanceAvailable: false,
    bedCount: 15,
    icuBedsAvailable: 0,
    description: "Health centre serving the Kasoa community.",
  },
  {
    name: "Prampram Health Centre",
    slug: "prampram-health-centre",
    type: "HEALTH_CENTRE",
    phone: "0303345678",
    email: "prampram.hc@ghs.gov.gh",
    address: "Prampram",
    city: "Prampram",
    districtName: "Ningo-Prampram District",
    latitude: 5.7234,
    longitude: 0.1234,
    nhisAccredited: true,
    emergencyCapable: false,
    ambulanceAvailable: false,
    bedCount: 10,
    icuBedsAvailable: 0,
    description: "Health centre serving Prampram and surrounding fishing communities.",
  },
  // Additional CHPS Compounds
  {
    name: "Osu CHPS Compound",
    slug: "osu-chps-compound",
    type: "CHPS_COMPOUND",
    phone: "0302778901",
    email: "osu.chps@ghs.gov.gh",
    address: "Osu",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.5523,
    longitude: -0.1823,
    nhisAccredited: true,
    emergencyCapable: false,
    ambulanceAvailable: false,
    bedCount: 4,
    icuBedsAvailable: 0,
    description: "Community-based health planning and services compound.",
  },
  {
    name: "Ablekuma CHPS Compound",
    slug: "ablekuma-chps-compound",
    type: "CHPS_COMPOUND",
    phone: "0302312345",
    email: "ablekuma.chps@ghs.gov.gh",
    address: "Ablekuma",
    city: "Accra",
    districtName: "Ablekuma West Municipal",
    latitude: 5.5412,
    longitude: -0.2678,
    nhisAccredited: true,
    emergencyCapable: false,
    ambulanceAvailable: false,
    bedCount: 4,
    icuBedsAvailable: 0,
    description: "CHPS compound serving the Ablekuma community.",
  },
  {
    name: "Dodowa CHPS Compound",
    slug: "dodowa-chps-compound",
    type: "CHPS_COMPOUND",
    phone: "0302567890",
    email: "dodowa.chps@ghs.gov.gh",
    address: "Dodowa",
    city: "Dodowa",
    districtName: "Shai-Osudoku District",
    latitude: 5.8812,
    longitude: -0.0789,
    nhisAccredited: true,
    emergencyCapable: false,
    ambulanceAvailable: false,
    bedCount: 4,
    icuBedsAvailable: 0,
    description: "CHPS compound serving Dodowa and surrounding areas.",
  },
  // Additional Pharmacies
  {
    name: "Alpha Pharmacy Spintex",
    slug: "alpha-pharmacy-spintex",
    type: "PHARMACY",
    phone: "0302813456",
    email: "spintex@alphapharmacy.com",
    address: "Spintex Road",
    city: "Accra",
    districtName: "Ledzokuku-Krowor",
    latitude: 5.6289,
    longitude: -0.0734,
    nhisAccredited: false,
    emergencyCapable: false,
    ambulanceAvailable: false,
    bedCount: 0,
    icuBedsAvailable: 0,
    description: "24-hour pharmacy on Spintex Road.",
  },
  {
    name: "HealthPlus Pharmacy East Legon",
    slug: "healthplus-pharmacy-east-legon",
    type: "PHARMACY",
    phone: "0302534567",
    email: "eastlegon@healthplus.com",
    address: "East Legon",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.6312,
    longitude: -0.1512,
    nhisAccredited: false,
    emergencyCapable: false,
    ambulanceAvailable: false,
    bedCount: 0,
    icuBedsAvailable: 0,
    description: "Modern pharmacy with wide range of medications.",
  },
  {
    name: "Lapaz Pharmacy",
    slug: "lapaz-pharmacy",
    type: "PHARMACY",
    phone: "0302423456",
    email: "info@lapazpharmacy.com",
    address: "Lapaz",
    city: "Accra",
    districtName: "Ga Central Municipal",
    latitude: 5.6034,
    longitude: -0.2489,
    nhisAccredited: false,
    emergencyCapable: false,
    ambulanceAvailable: false,
    bedCount: 0,
    icuBedsAvailable: 0,
    description: "Community pharmacy serving Lapaz residents.",
  },
  // Additional Diagnostic Centres
  {
    name: "Synlab Ghana",
    slug: "synlab-ghana-accra",
    type: "DIAGNOSTIC_CENTRE",
    phone: "0302789123",
    email: "info@synlab.com.gh",
    address: "Airport Residential",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.5756,
    longitude: -0.1789,
    nhisAccredited: true,
    emergencyCapable: false,
    ambulanceAvailable: false,
    bedCount: 0,
    icuBedsAvailable: 0,
    description: "International diagnostic laboratory with comprehensive testing services.",
  },
  {
    name: "Lancet Laboratories Ghana",
    slug: "lancet-laboratories-accra",
    type: "DIAGNOSTIC_CENTRE",
    phone: "0302761234",
    email: "info@lancet.com.gh",
    address: "Cantonments",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.5689,
    longitude: -0.1712,
    nhisAccredited: true,
    emergencyCapable: false,
    ambulanceAvailable: false,
    bedCount: 0,
    icuBedsAvailable: 0,
    description: "Leading pathology laboratory with advanced diagnostic capabilities.",
  },
  {
    name: "MDS Lancet Tema",
    slug: "mds-lancet-tema",
    type: "DIAGNOSTIC_CENTRE",
    phone: "0303223456",
    email: "tema@mdslancet.com",
    address: "Community 1",
    city: "Tema",
    districtName: "Tema Metropolitan",
    latitude: 5.6689,
    longitude: -0.0189,
    nhisAccredited: true,
    emergencyCapable: false,
    ambulanceAvailable: false,
    bedCount: 0,
    icuBedsAvailable: 0,
    description: "Diagnostic centre offering laboratory and imaging services in Tema.",
  },
];

type FacilityType = "HOSPITAL" | "CLINIC" | "PHARMACY" | "DIAGNOSTIC_CENTRE" | "MATERNITY_HOME" | "CHPS_COMPOUND" | "POLYCLINIC" | "HEALTH_CENTRE";

export async function POST() {
  try {
    const session = await auth();

    // Allow seeding without auth for initial setup, or require admin
    // if (session?.user?.role !== "MINISTRY_ADMIN") {
    //   return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    // }

    // Get or create Greater Accra region
    let greaterAccra = await db.region.findFirst({
      where: { name: "Greater Accra" },
    });

    if (!greaterAccra) {
      greaterAccra = await db.region.create({
        data: { name: "Greater Accra", code: "GA" },
      });
    }

    // Create districts
    const districts = [
      "Accra Metropolitan",
      "Tema Metropolitan",
      "Ledzokuku-Krowor",
      "La Dade-Kotopon",
      "Ashaiman Municipal",
      "Ga East Municipal",
      "Ga West Municipal",
      "Ga South Municipal",
      "Ga Central Municipal",
      "Ablekuma West Municipal",
      "Ayawaso North Municipal",
      "La Nkwantanang-Madina Municipal",
      "Adentan Municipal",
      "Ningo-Prampram District",
      "Shai-Osudoku District",
    ];

    const districtMap: Record<string, string> = {};

    for (const districtName of districts) {
      let district = await db.district.findFirst({
        where: { name: districtName, regionId: greaterAccra.id },
      });

      if (!district) {
        district = await db.district.create({
          data: { name: districtName, regionId: greaterAccra.id },
        });
      }
      districtMap[districtName] = district.id;
    }

    // Seed facilities
    let created = 0;
    let skipped = 0;

    for (const facility of FACILITIES) {
      const existing = await db.facility.findFirst({
        where: { slug: facility.slug },
      });

      if (existing) {
        skipped++;
        continue;
      }

      const districtId = districtMap[facility.districtName];
      if (!districtId) continue;

      await db.facility.create({
        data: {
          name: facility.name,
          slug: facility.slug,
          type: facility.type as FacilityType,
          licenseNumber: `GHS-${facility.type.substring(0, 3)}-${Date.now()}-${Math.random().toString(36).substring(7)}`,
          licenseDocumentUrl: "/documents/license-placeholder.pdf",
          phone: facility.phone,
          email: facility.email,
          address: facility.address,
          regionId: greaterAccra.id,
          districtId: districtId,
          latitude: facility.latitude,
          longitude: facility.longitude,
          nhisAccepted: facility.nhisAccredited,
          emergencyCapable: facility.emergencyCapable,
          ambulanceAvailable: facility.ambulanceAvailable,
          bedCount: facility.bedCount,
          icuBedsAvailable: facility.icuBedsAvailable,
          operatingHours: { open: "00:00", close: "23:59", is24Hours: facility.type === "HOSPITAL" },
          description: facility.description,
          status: "APPROVED",
          tier: facility.type === "HOSPITAL" ? "FOUR_STAR" : facility.type === "POLYCLINIC" ? "THREE_STAR" : "TWO_STAR",
          averageRating: 4.0 + Math.random() * 0.9,
          totalReviews: Math.floor(Math.random() * 50) + 10,
        },
      });

      created++;
    }

    return NextResponse.json({
      message: "Facilities seeded successfully",
      created,
      skipped,
      total: FACILITIES.length,
    });
  } catch (error) {
    console.error("Error seeding facilities:", error);
    return NextResponse.json(
      { error: "Failed to seed facilities" },
      { status: 500 }
    );
  }
}
