import { NextResponse } from "next/server";
import { db } from "@/lib/db";
import { auth } from "@/lib/auth";

// Greater Accra and Tema Healthcare Facilities
const FACILITIES = [
  // Hospitals in Greater Accra
  {
    name: "Korle Bu Teaching Hospital",
    slug: "korle-bu-teaching-hospital",
    type: "HOSPITAL",
    phone: "0302665401",
    email: "info@kfrh.gov.gh",
    address: "Guggisberg Avenue",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.5344,
    longitude: -0.2251,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 2000,
    icuBedsAvailable: 50,
    description: "Ghana's premier teaching hospital and the third largest hospital in Africa.",
  },
  {
    name: "37 Military Hospital",
    slug: "37-military-hospital",
    type: "HOSPITAL",
    phone: "0302776111",
    email: "info@37milhosp.gov.gh",
    address: "Liberation Road",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.5797,
    longitude: -0.1849,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 600,
    icuBedsAvailable: 30,
    description: "A military hospital that also serves civilians. Known for excellent trauma care.",
  },
  {
    name: "Ridge Hospital",
    slug: "ridge-hospital",
    type: "HOSPITAL",
    phone: "0302228315",
    email: "info@ridgehospital.gov.gh",
    address: "Castle Road, Ridge",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.5628,
    longitude: -0.1969,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 420,
    icuBedsAvailable: 20,
    description: "A major government hospital in the heart of Accra.",
  },
  {
    name: "Tema General Hospital",
    slug: "tema-general-hospital",
    type: "HOSPITAL",
    phone: "0303212222",
    email: "info@temageneralhospital.gov.gh",
    address: "Hospital Road, Community 1",
    city: "Tema",
    districtName: "Tema Metropolitan",
    latitude: 5.6698,
    longitude: -0.0166,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 350,
    icuBedsAvailable: 15,
    description: "The main government hospital serving Tema and surrounding communities.",
  },
  {
    name: "Lekma Hospital",
    slug: "lekma-hospital",
    type: "HOSPITAL",
    phone: "0302813456",
    email: "info@lekmahospital.gov.gh",
    address: "Teshie-Nungua",
    city: "Accra",
    districtName: "Ledzokuku-Krowor",
    latitude: 5.5922,
    longitude: -0.0975,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 200,
    icuBedsAvailable: 10,
    description: "A district hospital serving the Ledzokuku-Krowor Municipality.",
  },
  {
    name: "Nyaho Medical Centre",
    slug: "nyaho-medical-centre",
    type: "HOSPITAL",
    phone: "0302775341",
    email: "info@nyahomedical.com",
    address: "7th Avenue, Ridge",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.5612,
    longitude: -0.1891,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 80,
    icuBedsAvailable: 8,
    description: "A leading private hospital offering world-class healthcare services.",
  },
  {
    name: "Trust Hospital Osu",
    slug: "trust-hospital-osu",
    type: "HOSPITAL",
    phone: "0302761974",
    email: "info@trusthospitals.com",
    address: "Osu, Oxford Street",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.5571,
    longitude: -0.1818,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 60,
    icuBedsAvailable: 6,
    description: "A trusted private hospital chain with multiple locations across Accra.",
  },
  // Polyclinics
  {
    name: "Mamprobi Polyclinic",
    slug: "mamprobi-polyclinic",
    type: "POLYCLINIC",
    phone: "0302223456",
    email: "mamprobi.polyclinic@ghs.gov.gh",
    address: "Mamprobi",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.5389,
    longitude: -0.2356,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: false,
    bedCount: 40,
    icuBedsAvailable: 0,
    description: "A government polyclinic providing primary healthcare services.",
  },
  {
    name: "Tema Polyclinic",
    slug: "tema-polyclinic",
    type: "POLYCLINIC",
    phone: "0303215678",
    email: "tema.polyclinic@ghs.gov.gh",
    address: "Community 2",
    city: "Tema",
    districtName: "Tema Metropolitan",
    latitude: 5.6712,
    longitude: -0.0234,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: false,
    bedCount: 35,
    icuBedsAvailable: 0,
    description: "A government polyclinic serving the Tema community.",
  },
  {
    name: "La General Hospital",
    slug: "la-general-hospital",
    type: "POLYCLINIC",
    phone: "0302772345",
    email: "la.general@ghs.gov.gh",
    address: "La, Trade Fair",
    city: "Accra",
    districtName: "La Dade-Kotopon",
    latitude: 5.5756,
    longitude: -0.1567,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 100,
    icuBedsAvailable: 5,
    description: "A major polyclinic serving the La community.",
  },
  {
    name: "Ashaiman Polyclinic",
    slug: "ashaiman-polyclinic",
    type: "POLYCLINIC",
    phone: "0303305678",
    email: "ashaiman.polyclinic@ghs.gov.gh",
    address: "Ashaiman",
    city: "Ashaiman",
    districtName: "Ashaiman Municipal",
    latitude: 5.6912,
    longitude: -0.0345,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 50,
    icuBedsAvailable: 2,
    description: "The main government health facility serving Ashaiman Municipality.",
  },
  // Clinics
  {
    name: "Tema Community 5 Clinic",
    slug: "tema-community-5-clinic",
    type: "CLINIC",
    phone: "0303218901",
    email: "c5clinic@ghs.gov.gh",
    address: "Community 5",
    city: "Tema",
    districtName: "Tema Metropolitan",
    latitude: 5.6634,
    longitude: -0.0089,
    nhisAccredited: true,
    emergencyCapable: false,
    ambulanceAvailable: false,
    bedCount: 10,
    icuBedsAvailable: 0,
    description: "A community clinic providing basic healthcare services.",
  },
  {
    name: "Bethel Clinic Tema",
    slug: "bethel-clinic-tema",
    type: "CLINIC",
    phone: "0303219876",
    email: "info@bethelclinic.com",
    address: "Community 11",
    city: "Tema",
    districtName: "Tema Metropolitan",
    latitude: 5.6589,
    longitude: 0.0012,
    nhisAccredited: true,
    emergencyCapable: false,
    ambulanceAvailable: false,
    bedCount: 15,
    icuBedsAvailable: 0,
    description: "A private clinic offering quality healthcare services.",
  },
  // Health Centres
  {
    name: "Sakumono Health Centre",
    slug: "sakumono-health-centre",
    type: "HEALTH_CENTRE",
    phone: "0303456789",
    email: "sakumono.hc@ghs.gov.gh",
    address: "Sakumono Estate",
    city: "Tema",
    districtName: "Tema Metropolitan",
    latitude: 5.6234,
    longitude: -0.0456,
    nhisAccredited: true,
    emergencyCapable: false,
    ambulanceAvailable: false,
    bedCount: 8,
    icuBedsAvailable: 0,
    description: "A health centre providing primary healthcare to Sakumono residents.",
  },
  {
    name: "Lashibi Health Centre",
    slug: "lashibi-health-centre",
    type: "HEALTH_CENTRE",
    phone: "0303467890",
    email: "lashibi.hc@ghs.gov.gh",
    address: "Lashibi",
    city: "Tema",
    districtName: "Tema Metropolitan",
    latitude: 5.6345,
    longitude: -0.0567,
    nhisAccredited: true,
    emergencyCapable: false,
    ambulanceAvailable: false,
    bedCount: 6,
    icuBedsAvailable: 0,
    description: "A community health centre serving the Lashibi area.",
  },
  // Pharmacies
  {
    name: "Ernest Chemist Tema",
    slug: "ernest-chemist-tema",
    type: "PHARMACY",
    phone: "0303220123",
    email: "tema@ernestchemist.com",
    address: "Community 1, Main Road",
    city: "Tema",
    districtName: "Tema Metropolitan",
    latitude: 5.6701,
    longitude: -0.0178,
    nhisAccredited: false,
    emergencyCapable: false,
    ambulanceAvailable: false,
    bedCount: 0,
    icuBedsAvailable: 0,
    description: "A leading pharmacy chain providing quality medicines.",
  },
  {
    name: "Kama Pharmacy 24hr",
    slug: "kama-pharmacy-accra",
    type: "PHARMACY",
    phone: "0302789012",
    email: "info@kamapharmacy.com",
    address: "Osu, Cantonments",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.5612,
    longitude: -0.1756,
    nhisAccredited: false,
    emergencyCapable: false,
    ambulanceAvailable: false,
    bedCount: 0,
    icuBedsAvailable: 0,
    description: "A 24-hour pharmacy providing medicines and pharmaceutical services.",
  },
  // Diagnostic Centres
  {
    name: "Medlab Ghana Tema",
    slug: "medlab-ghana-tema",
    type: "DIAGNOSTIC_CENTRE",
    phone: "0303221234",
    email: "tema@medlabghana.com",
    address: "Community 2",
    city: "Tema",
    districtName: "Tema Metropolitan",
    latitude: 5.6723,
    longitude: -0.0212,
    nhisAccredited: true,
    emergencyCapable: false,
    ambulanceAvailable: false,
    bedCount: 0,
    icuBedsAvailable: 0,
    description: "A modern diagnostic centre offering laboratory and imaging services.",
  },
  {
    name: "Nyaho Diagnostic Centre",
    slug: "nyaho-diagnostic-centre",
    type: "DIAGNOSTIC_CENTRE",
    phone: "0302775342",
    email: "diagnostics@nyahomedical.com",
    address: "Airport Residential",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.5734,
    longitude: -0.1823,
    nhisAccredited: true,
    emergencyCapable: false,
    ambulanceAvailable: false,
    bedCount: 0,
    icuBedsAvailable: 0,
    description: "State-of-the-art diagnostic facility with advanced imaging services.",
  },
  // Maternity Homes
  {
    name: "Tema Maternity Home",
    slug: "tema-maternity-home",
    type: "MATERNITY_HOME",
    phone: "0303222345",
    email: "temamaternity@ghs.gov.gh",
    address: "Community 3",
    city: "Tema",
    districtName: "Tema Metropolitan",
    latitude: 5.6678,
    longitude: -0.0145,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: false,
    bedCount: 25,
    icuBedsAvailable: 2,
    description: "A specialized maternity facility providing antenatal and delivery care.",
  },
  {
    name: "Marie Stopes Accra",
    slug: "marie-stopes-accra",
    type: "MATERNITY_HOME",
    phone: "0302234567",
    email: "accra@mariestopes.org.gh",
    address: "Asylum Down",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.5567,
    longitude: -0.2123,
    nhisAccredited: true,
    emergencyCapable: false,
    ambulanceAvailable: false,
    bedCount: 15,
    icuBedsAvailable: 0,
    description: "Reproductive health clinic offering family planning and maternal health.",
  },
  // Additional Greater Accra Hospitals
  {
    name: "University of Ghana Medical Centre",
    slug: "university-of-ghana-medical-centre",
    type: "HOSPITAL",
    phone: "0302213850",
    email: "info@ugmc.ug.edu.gh",
    address: "Legon",
    city: "Accra",
    districtName: "Ga East Municipal",
    latitude: 5.6508,
    longitude: -0.1869,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 650,
    icuBedsAvailable: 40,
    description: "A state-of-the-art teaching hospital affiliated with the University of Ghana.",
  },
  {
    name: "Police Hospital",
    slug: "police-hospital-accra",
    type: "HOSPITAL",
    phone: "0302773906",
    email: "info@policehospital.gov.gh",
    address: "Cantonments",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.5678,
    longitude: -0.1734,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 200,
    icuBedsAvailable: 12,
    description: "Ghana Police Service hospital also serving the general public.",
  },
  {
    name: "Achimota Hospital",
    slug: "achimota-hospital",
    type: "HOSPITAL",
    phone: "0302401234",
    email: "info@achimotahospital.gov.gh",
    address: "Achimota",
    city: "Accra",
    districtName: "Ga West Municipal",
    latitude: 5.6156,
    longitude: -0.2289,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 180,
    icuBedsAvailable: 8,
    description: "A district hospital serving Achimota and surrounding communities.",
  },
  {
    name: "Ga South Municipal Hospital",
    slug: "ga-south-municipal-hospital",
    type: "HOSPITAL",
    phone: "0302945678",
    email: "info@gasouthhospital.gov.gh",
    address: "Weija",
    city: "Accra",
    districtName: "Ga South Municipal",
    latitude: 5.5567,
    longitude: -0.3234,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 150,
    icuBedsAvailable: 6,
    description: "Municipal hospital serving the Ga South district.",
  },
  {
    name: "Pantang Hospital",
    slug: "pantang-hospital",
    type: "HOSPITAL",
    phone: "0302506789",
    email: "info@pantanghospital.gov.gh",
    address: "Pantang",
    city: "Accra",
    districtName: "Ga East Municipal",
    latitude: 5.6789,
    longitude: -0.1567,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 500,
    icuBedsAvailable: 10,
    description: "A psychiatric hospital providing mental health services.",
  },
  {
    name: "Amasaman Government Hospital",
    slug: "amasaman-government-hospital",
    type: "HOSPITAL",
    phone: "0302956789",
    email: "info@amasamanhospital.gov.gh",
    address: "Amasaman",
    city: "Accra",
    districtName: "Ga West Municipal",
    latitude: 5.7012,
    longitude: -0.2789,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 120,
    icuBedsAvailable: 5,
    description: "Government hospital serving Ga West Municipality.",
  },
  {
    name: "Legon Hospital",
    slug: "legon-hospital",
    type: "HOSPITAL",
    phone: "0302500381",
    email: "info@legonhospital.ug.edu.gh",
    address: "University of Ghana, Legon",
    city: "Accra",
    districtName: "Ga East Municipal",
    latitude: 5.6478,
    longitude: -0.1856,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 80,
    icuBedsAvailable: 4,
    description: "University hospital serving students and the Legon community.",
  },
  {
    name: "Cocoa Clinic",
    slug: "cocoa-clinic-accra",
    type: "HOSPITAL",
    phone: "0302228888",
    email: "info@cocoaclinic.com",
    address: "Cantonments",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.5712,
    longitude: -0.1678,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 100,
    icuBedsAvailable: 8,
    description: "A well-established private hospital with comprehensive healthcare services.",
  },
  {
    name: "Euracare Advanced Diagnostics & Heart Centre",
    slug: "euracare-heart-centre",
    type: "HOSPITAL",
    phone: "0302739393",
    email: "info@euracareghana.com",
    address: "Airport Residential Area",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.5789,
    longitude: -0.1812,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 50,
    icuBedsAvailable: 10,
    description: "Specialized cardiac care and advanced diagnostic centre.",
  },
  {
    name: "Rabito Clinic",
    slug: "rabito-clinic-accra",
    type: "HOSPITAL",
    phone: "0302784848",
    email: "info@rabitoclinic.com",
    address: "Osu",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.5534,
    longitude: -0.1789,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 40,
    icuBedsAvailable: 4,
    description: "Private hospital known for quality healthcare and fertility services.",
  },
  {
    name: "Medifem Multi-Specialist Hospital",
    slug: "medifem-hospital",
    type: "HOSPITAL",
    phone: "0302817272",
    email: "info@medifemhospital.com",
    address: "East Legon",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.6234,
    longitude: -0.1567,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 60,
    icuBedsAvailable: 6,
    description: "Multi-specialist hospital with focus on women's health and fertility.",
  },
  {
    name: "The Bank Hospital",
    slug: "the-bank-hospital",
    type: "HOSPITAL",
    phone: "0302610300",
    email: "info@thebankhospital.com",
    address: "North Ridge",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.5656,
    longitude: -0.2012,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 70,
    icuBedsAvailable: 8,
    description: "Premium private hospital offering comprehensive medical services.",
  },
  {
    name: "Akai House Clinic",
    slug: "akai-house-clinic",
    type: "HOSPITAL",
    phone: "0302763972",
    email: "info@akaihouseclinic.com",
    address: "Airport Residential",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.5801,
    longitude: -0.1756,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 45,
    icuBedsAvailable: 5,
    description: "Private clinic offering specialized medical care.",
  },
  // Additional Polyclinics
  {
    name: "Kaneshie Polyclinic",
    slug: "kaneshie-polyclinic",
    type: "POLYCLINIC",
    phone: "0302229876",
    email: "kaneshie.polyclinic@ghs.gov.gh",
    address: "Kaneshie",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.5534,
    longitude: -0.2345,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 60,
    icuBedsAvailable: 3,
    description: "Government polyclinic serving the Kaneshie community.",
  },
  {
    name: "Dansoman Polyclinic",
    slug: "dansoman-polyclinic",
    type: "POLYCLINIC",
    phone: "0302311234",
    email: "dansoman.polyclinic@ghs.gov.gh",
    address: "Dansoman",
    city: "Accra",
    districtName: "Ablekuma West Municipal",
    latitude: 5.5312,
    longitude: -0.2567,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 55,
    icuBedsAvailable: 2,
    description: "Government polyclinic serving Dansoman and surrounding areas.",
  },
  {
    name: "Maamobi General Hospital",
    slug: "maamobi-general-hospital",
    type: "POLYCLINIC",
    phone: "0302245678",
    email: "maamobi.hospital@ghs.gov.gh",
    address: "Maamobi",
    city: "Accra",
    districtName: "Ayawaso North Municipal",
    latitude: 5.5789,
    longitude: -0.2123,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 80,
    icuBedsAvailable: 4,
    description: "General hospital serving the Maamobi community.",
  },
  {
    name: "Adabraka Polyclinic",
    slug: "adabraka-polyclinic",
    type: "POLYCLINIC",
    phone: "0302224567",
    email: "adabraka.polyclinic@ghs.gov.gh",
    address: "Adabraka",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.5567,
    longitude: -0.2089,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: false,
    bedCount: 45,
    icuBedsAvailable: 2,
    description: "Government polyclinic in the heart of Adabraka.",
  },
  {
    name: "Madina Polyclinic",
    slug: "madina-polyclinic",
    type: "POLYCLINIC",
    phone: "0302512345",
    email: "madina.polyclinic@ghs.gov.gh",
    address: "Madina",
    city: "Accra",
    districtName: "La Nkwantanang-Madina Municipal",
    latitude: 5.6712,
    longitude: -0.1678,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 70,
    icuBedsAvailable: 3,
    description: "Government polyclinic serving the Madina community.",
  },
  {
    name: "Kpeshie Polyclinic",
    slug: "kpeshie-polyclinic",
    type: "POLYCLINIC",
    phone: "0302713456",
    email: "kpeshie.polyclinic@ghs.gov.gh",
    address: "Kpeshie",
    city: "Accra",
    districtName: "La Dade-Kotopon",
    latitude: 5.5889,
    longitude: -0.1234,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: false,
    bedCount: 40,
    icuBedsAvailable: 2,
    description: "Government polyclinic serving the Kpeshie area.",
  },
  // Additional Clinics
  {
    name: "Spintex Medical Centre",
    slug: "spintex-medical-centre",
    type: "CLINIC",
    phone: "0302812345",
    email: "info@spintexmedical.com",
    address: "Spintex Road",
    city: "Accra",
    districtName: "Ledzokuku-Krowor",
    latitude: 5.6234,
    longitude: -0.0789,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: false,
    bedCount: 25,
    icuBedsAvailable: 2,
    description: "Private medical centre on Spintex Road.",
  },
  {
    name: "East Legon Medical Centre",
    slug: "east-legon-medical-centre",
    type: "CLINIC",
    phone: "0302523456",
    email: "info@eastlegonmedical.com",
    address: "East Legon",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.6345,
    longitude: -0.1456,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: false,
    bedCount: 20,
    icuBedsAvailable: 2,
    description: "Private clinic serving the East Legon community.",
  },
  {
    name: "Lapaz Community Clinic",
    slug: "lapaz-community-clinic",
    type: "CLINIC",
    phone: "0302412345",
    email: "lapaz.clinic@ghs.gov.gh",
    address: "Lapaz",
    city: "Accra",
    districtName: "Ga Central Municipal",
    latitude: 5.6012,
    longitude: -0.2456,
    nhisAccredited: true,
    emergencyCapable: false,
    ambulanceAvailable: false,
    bedCount: 15,
    icuBedsAvailable: 0,
    description: "Community clinic serving Lapaz residents.",
  },
  {
    name: "Teshie Clinic",
    slug: "teshie-clinic",
    type: "CLINIC",
    phone: "0302714567",
    email: "teshie.clinic@ghs.gov.gh",
    address: "Teshie",
    city: "Accra",
    districtName: "Ledzokuku-Krowor",
    latitude: 5.5834,
    longitude: -0.1089,
    nhisAccredited: true,
    emergencyCapable: false,
    ambulanceAvailable: false,
    bedCount: 12,
    icuBedsAvailable: 0,
    description: "Government clinic serving the Teshie community.",
  },
  {
    name: "Nungua Clinic",
    slug: "nungua-clinic",
    type: "CLINIC",
    phone: "0302715678",
    email: "nungua.clinic@ghs.gov.gh",
    address: "Nungua",
    city: "Accra",
    districtName: "Ledzokuku-Krowor",
    latitude: 5.5912,
    longitude: -0.0856,
    nhisAccredited: true,
    emergencyCapable: false,
    ambulanceAvailable: false,
    bedCount: 10,
    icuBedsAvailable: 0,
    description: "Government clinic serving the Nungua community.",
  },
  // Additional Health Centres
  {
    name: "Dome Health Centre",
    slug: "dome-health-centre",
    type: "HEALTH_CENTRE",
    phone: "0302413456",
    email: "dome.hc@ghs.gov.gh",
    address: "Dome",
    city: "Accra",
    districtName: "Ga East Municipal",
    latitude: 5.6456,
    longitude: -0.2234,
    nhisAccredited: true,
    emergencyCapable: false,
    ambulanceAvailable: false,
    bedCount: 10,
    icuBedsAvailable: 0,
    description: "Health centre serving the Dome community.",
  },
  {
    name: "Kwabenya Health Centre",
    slug: "kwabenya-health-centre",
    type: "HEALTH_CENTRE",
    phone: "0302514567",
    email: "kwabenya.hc@ghs.gov.gh",
    address: "Kwabenya",
    city: "Accra",
    districtName: "Ga East Municipal",
    latitude: 5.6789,
    longitude: -0.2012,
    nhisAccredited: true,
    emergencyCapable: false,
    ambulanceAvailable: false,
    bedCount: 8,
    icuBedsAvailable: 0,
    description: "Health centre serving Kwabenya and surrounding areas.",
  },
  {
    name: "Adenta Health Centre",
    slug: "adenta-health-centre",
    type: "HEALTH_CENTRE",
    phone: "0302523456",
    email: "adenta.hc@ghs.gov.gh",
    address: "Adenta",
    city: "Accra",
    districtName: "Adentan Municipal",
    latitude: 5.7012,
    longitude: -0.1567,
    nhisAccredited: true,
    emergencyCapable: false,
    ambulanceAvailable: false,
    bedCount: 12,
    icuBedsAvailable: 0,
    description: "Health centre serving the Adenta community.",
  },
  {
    name: "Kasoa Health Centre",
    slug: "kasoa-health-centre",
    type: "HEALTH_CENTRE",
    phone: "0302934567",
    email: "kasoa.hc@ghs.gov.gh",
    address: "Kasoa",
    city: "Kasoa",
    districtName: "Ga South Municipal",
    latitude: 5.5234,
    longitude: -0.4234,
    nhisAccredited: true,
    emergencyCapable: false,
    ambulanceAvailable: false,
    bedCount: 15,
    icuBedsAvailable: 0,
    description: "Health centre serving the Kasoa community.",
  },
  {
    name: "Prampram Health Centre",
    slug: "prampram-health-centre",
    type: "HEALTH_CENTRE",
    phone: "0303345678",
    email: "prampram.hc@ghs.gov.gh",
    address: "Prampram",
    city: "Prampram",
    districtName: "Ningo-Prampram District",
    latitude: 5.7234,
    longitude: 0.1234,
    nhisAccredited: true,
    emergencyCapable: false,
    ambulanceAvailable: false,
    bedCount: 10,
    icuBedsAvailable: 0,
    description: "Health centre serving Prampram and surrounding fishing communities.",
  },
  // Additional CHPS Compounds
  {
    name: "Osu CHPS Compound",
    slug: "osu-chps-compound",
    type: "CHPS_COMPOUND",
    phone: "0302778901",
    email: "osu.chps@ghs.gov.gh",
    address: "Osu",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.5523,
    longitude: -0.1823,
    nhisAccredited: true,
    emergencyCapable: false,
    ambulanceAvailable: false,
    bedCount: 4,
    icuBedsAvailable: 0,
    description: "Community-based health planning and services compound.",
  },
  {
    name: "Ablekuma CHPS Compound",
    slug: "ablekuma-chps-compound",
    type: "CHPS_COMPOUND",
    phone: "0302312345",
    email: "ablekuma.chps@ghs.gov.gh",
    address: "Ablekuma",
    city: "Accra",
    districtName: "Ablekuma West Municipal",
    latitude: 5.5412,
    longitude: -0.2678,
    nhisAccredited: true,
    emergencyCapable: false,
    ambulanceAvailable: false,
    bedCount: 4,
    icuBedsAvailable: 0,
    description: "CHPS compound serving the Ablekuma community.",
  },
  {
    name: "Dodowa CHPS Compound",
    slug: "dodowa-chps-compound",
    type: "CHPS_COMPOUND",
    phone: "0302567890",
    email: "dodowa.chps@ghs.gov.gh",
    address: "Dodowa",
    city: "Dodowa",
    districtName: "Shai-Osudoku District",
    latitude: 5.8812,
    longitude: -0.0789,
    nhisAccredited: true,
    emergencyCapable: false,
    ambulanceAvailable: false,
    bedCount: 4,
    icuBedsAvailable: 0,
    description: "CHPS compound serving Dodowa and surrounding areas.",
  },
  // Additional Pharmacies
  {
    name: "Alpha Pharmacy Spintex",
    slug: "alpha-pharmacy-spintex",
    type: "PHARMACY",
    phone: "0302813456",
    email: "spintex@alphapharmacy.com",
    address: "Spintex Road",
    city: "Accra",
    districtName: "Ledzokuku-Krowor",
    latitude: 5.6289,
    longitude: -0.0734,
    nhisAccredited: false,
    emergencyCapable: false,
    ambulanceAvailable: false,
    bedCount: 0,
    icuBedsAvailable: 0,
    description: "24-hour pharmacy on Spintex Road.",
  },
  {
    name: "HealthPlus Pharmacy East Legon",
    slug: "healthplus-pharmacy-east-legon",
    type: "PHARMACY",
    phone: "0302534567",
    email: "eastlegon@healthplus.com",
    address: "East Legon",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.6312,
    longitude: -0.1512,
    nhisAccredited: false,
    emergencyCapable: false,
    ambulanceAvailable: false,
    bedCount: 0,
    icuBedsAvailable: 0,
    description: "Modern pharmacy with wide range of medications.",
  },
  {
    name: "Lapaz Pharmacy",
    slug: "lapaz-pharmacy",
    type: "PHARMACY",
    phone: "0302423456",
    email: "info@lapazpharmacy.com",
    address: "Lapaz",
    city: "Accra",
    districtName: "Ga Central Municipal",
    latitude: 5.6034,
    longitude: -0.2489,
    nhisAccredited: false,
    emergencyCapable: false,
    ambulanceAvailable: false,
    bedCount: 0,
    icuBedsAvailable: 0,
    description: "Community pharmacy serving Lapaz residents.",
  },
  // Additional Diagnostic Centres
  {
    name: "Synlab Ghana",
    slug: "synlab-ghana-accra",
    type: "DIAGNOSTIC_CENTRE",
    phone: "0302789123",
    email: "info@synlab.com.gh",
    address: "Airport Residential",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.5756,
    longitude: -0.1789,
    nhisAccredited: true,
    emergencyCapable: false,
    ambulanceAvailable: false,
    bedCount: 0,
    icuBedsAvailable: 0,
    description: "International diagnostic laboratory with comprehensive testing services.",
  },
  {
    name: "Lancet Laboratories Ghana",
    slug: "lancet-laboratories-accra",
    type: "DIAGNOSTIC_CENTRE",
    phone: "0302761234",
    email: "info@lancet.com.gh",
    address: "Cantonments",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.5689,
    longitude: -0.1712,
    nhisAccredited: true,
    emergencyCapable: false,
    ambulanceAvailable: false,
    bedCount: 0,
    icuBedsAvailable: 0,
    description: "Leading pathology laboratory with advanced diagnostic capabilities.",
  },
  {
    name: "MDS Lancet Tema",
    slug: "mds-lancet-tema",
    type: "DIAGNOSTIC_CENTRE",
    phone: "0303223456",
    email: "tema@mdslancet.com",
    address: "Community 1",
    city: "Tema",
    districtName: "Tema Metropolitan",
    latitude: 5.6689,
    longitude: -0.0189,
    nhisAccredited: true,
    emergencyCapable: false,
    ambulanceAvailable: false,
    bedCount: 0,
    icuBedsAvailable: 0,
    description: "Diagnostic centre offering laboratory and imaging services in Tema.",
  },
  // ============================================
  // COMPREHENSIVE GREATER ACCRA HOSPITALS LIST
  // ============================================
  // Government/Public Hospitals
  {
    name: "La General Hospital",
    slug: "la-general-hospital",
    type: "HOSPITAL",
    phone: "0302772345",
    email: "info@lageneralhospital.gov.gh",
    address: "La",
    city: "Accra",
    districtName: "La Dade-Kotopon",
    latitude: 5.5456,
    longitude: -0.1567,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 150,
    icuBedsAvailable: 8,
    description: "Government hospital serving La and surrounding communities.",
  },
  {
    name: "Ashaiman Polyclinic",
    slug: "ashaiman-polyclinic",
    type: "HOSPITAL",
    phone: "0303301234",
    email: "ashaiman.polyclinic@ghs.gov.gh",
    address: "Ashaiman",
    city: "Ashaiman",
    districtName: "Ashaiman Municipal",
    latitude: 5.6912,
    longitude: -0.0312,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 100,
    icuBedsAvailable: 5,
    description: "Main government health facility serving Ashaiman Municipality.",
  },
  {
    name: "Mamprobi Polyclinic",
    slug: "mamprobi-polyclinic",
    type: "HOSPITAL",
    phone: "0302668901",
    email: "mamprobi.polyclinic@ghs.gov.gh",
    address: "Mamprobi",
    city: "Accra",
    districtName: "Ablekuma West Municipal",
    latitude: 5.5234,
    longitude: -0.2345,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 80,
    icuBedsAvailable: 4,
    description: "Government polyclinic serving Mamprobi and Korle Gonno areas.",
  },
  {
    name: "Ussher Polyclinic",
    slug: "ussher-polyclinic",
    type: "HOSPITAL",
    phone: "0302667890",
    email: "ussher.polyclinic@ghs.gov.gh",
    address: "Ussher Town",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.5312,
    longitude: -0.2089,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: false,
    bedCount: 60,
    icuBedsAvailable: 3,
    description: "Government polyclinic in the historic Ussher Town area.",
  },
  {
    name: "Princess Marie Louise Hospital",
    slug: "princess-marie-louise-hospital",
    type: "HOSPITAL",
    phone: "0302663456",
    email: "pml.hospital@ghs.gov.gh",
    address: "Korle Gonno",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.5289,
    longitude: -0.2234,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 120,
    icuBedsAvailable: 6,
    description: "Children's hospital providing pediatric care services.",
  },
  {
    name: "Accra Psychiatric Hospital",
    slug: "accra-psychiatric-hospital",
    type: "HOSPITAL",
    phone: "0302228765",
    email: "info@accrapsy.gov.gh",
    address: "Adabraka",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.5534,
    longitude: -0.2156,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 400,
    icuBedsAvailable: 5,
    description: "National psychiatric hospital providing mental health services.",
  },
  {
    name: "Dodowa District Hospital",
    slug: "dodowa-district-hospital",
    type: "HOSPITAL",
    phone: "0302890123",
    email: "dodowa.hospital@ghs.gov.gh",
    address: "Dodowa",
    city: "Dodowa",
    districtName: "Shai-Osudoku District",
    latitude: 5.8812,
    longitude: -0.0956,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 100,
    icuBedsAvailable: 4,
    description: "District hospital serving Shai-Osudoku and surrounding areas.",
  },
  {
    name: "Prampram Health Centre",
    slug: "prampram-health-centre-hospital",
    type: "HOSPITAL",
    phone: "0303456789",
    email: "prampram.health@ghs.gov.gh",
    address: "Prampram",
    city: "Prampram",
    districtName: "Ningo-Prampram District",
    latitude: 5.7234,
    longitude: 0.1123,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 60,
    icuBedsAvailable: 2,
    description: "Health centre serving Prampram and Ningo communities.",
  },
  {
    name: "Adentan Municipal Hospital",
    slug: "adentan-municipal-hospital",
    type: "HOSPITAL",
    phone: "0302523456",
    email: "adentan.hospital@ghs.gov.gh",
    address: "Adentan",
    city: "Accra",
    districtName: "Adentan Municipal",
    latitude: 5.7123,
    longitude: -0.1456,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 120,
    icuBedsAvailable: 6,
    description: "Municipal hospital serving Adentan and surrounding communities.",
  },
  // Private Hospitals
  {
    name: "Trust Hospital",
    slug: "trust-hospital-osu",
    type: "HOSPITAL",
    phone: "0302761974",
    email: "info@trusthospital.com.gh",
    address: "Osu",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.5567,
    longitude: -0.1823,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 80,
    icuBedsAvailable: 10,
    description: "Leading private hospital with comprehensive healthcare services.",
  },
  {
    name: "Lister Hospital & Fertility Centre",
    slug: "lister-hospital-fertility-centre",
    type: "HOSPITAL",
    phone: "0302812299",
    email: "info@listerhospital.com.gh",
    address: "Airport Residential",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.5823,
    longitude: -0.1789,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 60,
    icuBedsAvailable: 8,
    description: "Specialist hospital known for fertility treatments and general care.",
  },
  {
    name: "Nyaho Takoradi Clinic",
    slug: "nyaho-clinic-east-legon",
    type: "HOSPITAL",
    phone: "0302544615",
    email: "eastlegon@nyahomedical.com",
    address: "East Legon",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.6312,
    longitude: -0.1534,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 40,
    icuBedsAvailable: 5,
    description: "Branch of Nyaho Medical Centre in East Legon.",
  },
  {
    name: "Holy Trinity Medical Centre",
    slug: "holy-trinity-medical-centre",
    type: "HOSPITAL",
    phone: "0302234890",
    email: "info@holytrinitymedical.com",
    address: "Baatsona",
    city: "Accra",
    districtName: "Ledzokuku-Krowor",
    latitude: 5.6345,
    longitude: -0.0567,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 50,
    icuBedsAvailable: 4,
    description: "Private hospital providing quality healthcare in Spintex area.",
  },
  {
    name: "Gicel Hospital",
    slug: "gicel-hospital",
    type: "HOSPITAL",
    phone: "0302815678",
    email: "info@gicelhospital.com",
    address: "East Legon",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.6278,
    longitude: -0.1612,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 45,
    icuBedsAvailable: 5,
    description: "Modern private hospital with specialist services.",
  },
  {
    name: "Lapaz Community Hospital",
    slug: "lapaz-community-hospital",
    type: "HOSPITAL",
    phone: "0302412345",
    email: "info@lapazhospital.com",
    address: "Lapaz",
    city: "Accra",
    districtName: "Ga Central Municipal",
    latitude: 5.6089,
    longitude: -0.2456,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 70,
    icuBedsAvailable: 4,
    description: "Community hospital serving Lapaz and Abeka areas.",
  },
  {
    name: "Finney Hospital",
    slug: "finney-hospital",
    type: "HOSPITAL",
    phone: "0302234567",
    email: "info@finneyhospital.com",
    address: "Tesano",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.5912,
    longitude: -0.2234,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 55,
    icuBedsAvailable: 4,
    description: "Private hospital providing comprehensive medical services.",
  },
  {
    name: "Bethel Hospital",
    slug: "bethel-hospital-accra",
    type: "HOSPITAL",
    phone: "0302301234",
    email: "info@bethelhospital.com.gh",
    address: "Dansoman",
    city: "Accra",
    districtName: "Ablekuma West Municipal",
    latitude: 5.5234,
    longitude: -0.2512,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 60,
    icuBedsAvailable: 4,
    description: "Private hospital serving Dansoman and surrounding communities.",
  },
  {
    name: "Tema Women's Hospital",
    slug: "tema-womens-hospital",
    type: "HOSPITAL",
    phone: "0303212890",
    email: "info@temawomenshospital.com",
    address: "Community 2",
    city: "Tema",
    districtName: "Tema Metropolitan",
    latitude: 5.6712,
    longitude: -0.0234,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 80,
    icuBedsAvailable: 6,
    description: "Specialist hospital for women's health and maternity care.",
  },
  {
    name: "Sakumono Baptist Hospital",
    slug: "sakumono-baptist-hospital",
    type: "HOSPITAL",
    phone: "0303301890",
    email: "info@sakumonobaptist.org",
    address: "Sakumono",
    city: "Tema",
    districtName: "Tema Metropolitan",
    latitude: 5.6234,
    longitude: -0.0123,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 70,
    icuBedsAvailable: 5,
    description: "Mission hospital providing quality healthcare services.",
  },
  {
    name: "Meridian Hospital",
    slug: "meridian-hospital-tema",
    type: "HOSPITAL",
    phone: "0303215678",
    email: "info@meridianhospital.com.gh",
    address: "Community 11",
    city: "Tema",
    districtName: "Tema Metropolitan",
    latitude: 5.6534,
    longitude: -0.0089,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 50,
    icuBedsAvailable: 4,
    description: "Private hospital with modern facilities in Tema.",
  },
  {
    name: "Nana Ama Clinic & Maternity",
    slug: "nana-ama-clinic-maternity",
    type: "HOSPITAL",
    phone: "0302678901",
    email: "info@nanaamaclinic.com",
    address: "Teshie",
    city: "Accra",
    districtName: "Ledzokuku-Krowor",
    latitude: 5.5834,
    longitude: -0.1012,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: false,
    bedCount: 35,
    icuBedsAvailable: 2,
    description: "Clinic and maternity home serving Teshie community.",
  },
  {
    name: "Nungua Polyclinic",
    slug: "nungua-polyclinic",
    type: "HOSPITAL",
    phone: "0302712890",
    email: "nungua.polyclinic@ghs.gov.gh",
    address: "Nungua",
    city: "Accra",
    districtName: "Ledzokuku-Krowor",
    latitude: 5.5912,
    longitude: -0.0789,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 65,
    icuBedsAvailable: 3,
    description: "Government polyclinic serving Nungua and surrounding areas.",
  },
  {
    name: "Weija-Gbawe Municipal Hospital",
    slug: "weija-gbawe-municipal-hospital",
    type: "HOSPITAL",
    phone: "0302945123",
    email: "weija.hospital@ghs.gov.gh",
    address: "Weija",
    city: "Accra",
    districtName: "Ga South Municipal",
    latitude: 5.5512,
    longitude: -0.3312,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 100,
    icuBedsAvailable: 5,
    description: "Municipal hospital serving Weija-Gbawe and surrounding areas.",
  },
  {
    name: "Kasoa Polyclinic",
    slug: "kasoa-polyclinic",
    type: "HOSPITAL",
    phone: "0302912345",
    email: "kasoa.polyclinic@ghs.gov.gh",
    address: "Kasoa",
    city: "Kasoa",
    districtName: "Ga South Municipal",
    latitude: 5.5334,
    longitude: -0.4234,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 80,
    icuBedsAvailable: 4,
    description: "Government polyclinic serving the rapidly growing Kasoa area.",
  },
  {
    name: "St. Joseph's Hospital Koforidua",
    slug: "st-josephs-hospital-dodowa",
    type: "HOSPITAL",
    phone: "0302890456",
    email: "info@stjosephsdodowa.org",
    address: "Dodowa",
    city: "Dodowa",
    districtName: "Shai-Osudoku District",
    latitude: 5.8756,
    longitude: -0.0912,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 60,
    icuBedsAvailable: 3,
    description: "Catholic mission hospital providing healthcare services.",
  },
  {
    name: "Atomic Energy Hospital",
    slug: "atomic-energy-hospital",
    type: "HOSPITAL",
    phone: "0302400123",
    email: "info@atomichospital.gov.gh",
    address: "Atomic Junction",
    city: "Accra",
    districtName: "Ga East Municipal",
    latitude: 5.6456,
    longitude: -0.2123,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 80,
    icuBedsAvailable: 5,
    description: "Hospital affiliated with Ghana Atomic Energy Commission.",
  },
  {
    name: "Madina Hospital",
    slug: "madina-hospital",
    type: "HOSPITAL",
    phone: "0302520123",
    email: "info@madinahospital.com",
    address: "Madina",
    city: "Accra",
    districtName: "La Nkwantanang-Madina Municipal",
    latitude: 5.6789,
    longitude: -0.1712,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 70,
    icuBedsAvailable: 4,
    description: "Private hospital serving Madina and surrounding communities.",
  },
  {
    name: "Haatso Polyclinic",
    slug: "haatso-polyclinic",
    type: "HOSPITAL",
    phone: "0302530456",
    email: "haatso.polyclinic@ghs.gov.gh",
    address: "Haatso",
    city: "Accra",
    districtName: "Ga East Municipal",
    latitude: 5.6612,
    longitude: -0.1934,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 50,
    icuBedsAvailable: 3,
    description: "Government polyclinic serving Haatso and Atomic areas.",
  },
  {
    name: "Dzorwulu Medical Centre",
    slug: "dzorwulu-medical-centre",
    type: "HOSPITAL",
    phone: "0302774567",
    email: "info@dzorwulumedical.com",
    address: "Dzorwulu",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.5934,
    longitude: -0.1956,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 40,
    icuBedsAvailable: 4,
    description: "Private medical centre with specialist services.",
  },
  {
    name: "Osu Children's Hospital",
    slug: "osu-childrens-hospital",
    type: "HOSPITAL",
    phone: "0302775890",
    email: "info@osuchildrens.org",
    address: "Osu",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.5512,
    longitude: -0.1756,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 60,
    icuBedsAvailable: 6,
    description: "Specialized pediatric hospital for children's healthcare.",
  },
  {
    name: "Accra Regional Hospital",
    slug: "accra-regional-hospital",
    type: "HOSPITAL",
    phone: "0302228456",
    email: "info@accraregional.gov.gh",
    address: "Ridge",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.5612,
    longitude: -0.1989,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 300,
    icuBedsAvailable: 15,
    description: "Regional referral hospital serving Greater Accra.",
  },
  {
    name: "Spintex Hospital",
    slug: "spintex-hospital",
    type: "HOSPITAL",
    phone: "0302823456",
    email: "info@spintexhospital.com",
    address: "Spintex Road",
    city: "Accra",
    districtName: "Ledzokuku-Krowor",
    latitude: 5.6312,
    longitude: -0.0656,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 55,
    icuBedsAvailable: 5,
    description: "Private hospital serving the Spintex community.",
  },
  {
    name: "Baatsona Hospital",
    slug: "baatsona-hospital",
    type: "HOSPITAL",
    phone: "0302834567",
    email: "info@baatsonahospital.com",
    address: "Baatsona",
    city: "Accra",
    districtName: "Ledzokuku-Krowor",
    latitude: 5.6389,
    longitude: -0.0512,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 45,
    icuBedsAvailable: 4,
    description: "Private hospital in the Baatsona area.",
  },
  {
    name: "Afram Hospital",
    slug: "afram-hospital",
    type: "HOSPITAL",
    phone: "0302845678",
    email: "info@aframhospital.com",
    address: "Dansoman",
    city: "Accra",
    districtName: "Ablekuma West Municipal",
    latitude: 5.5189,
    longitude: -0.2589,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 50,
    icuBedsAvailable: 3,
    description: "Private hospital serving Dansoman and surrounding areas.",
  },
  {
    name: "Kaneshie Hospital",
    slug: "kaneshie-hospital",
    type: "HOSPITAL",
    phone: "0302230123",
    email: "info@kaneshiehospital.com",
    address: "Kaneshie",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.5489,
    longitude: -0.2389,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 60,
    icuBedsAvailable: 4,
    description: "Private hospital in the Kaneshie area.",
  },
  {
    name: "Osu Klottey Hospital",
    slug: "osu-klottey-hospital",
    type: "HOSPITAL",
    phone: "0302776234",
    email: "info@osuklotteyhospital.com",
    address: "Osu",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.5534,
    longitude: -0.1812,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 45,
    icuBedsAvailable: 4,
    description: "Private hospital serving the Osu community.",
  },
  {
    name: "Airport West Hospital",
    slug: "airport-west-hospital",
    type: "HOSPITAL",
    phone: "0302777345",
    email: "info@airportwesthospital.com",
    address: "Airport West",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.5867,
    longitude: -0.1889,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 50,
    icuBedsAvailable: 5,
    description: "Private hospital near Kotoka International Airport.",
  },
  {
    name: "Cantonments Hospital",
    slug: "cantonments-hospital",
    type: "HOSPITAL",
    phone: "0302778456",
    email: "info@cantonmentshospital.com",
    address: "Cantonments",
    city: "Accra",
    districtName: "Accra Metropolitan",
    latitude: 5.5712,
    longitude: -0.1712,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 55,
    icuBedsAvailable: 5,
    description: "Private hospital in the Cantonments area.",
  },
  {
    name: "Adenta Hospital",
    slug: "adenta-hospital",
    type: "HOSPITAL",
    phone: "0302524567",
    email: "info@adentahospital.com",
    address: "Adenta",
    city: "Accra",
    districtName: "Adentan Municipal",
    latitude: 5.7089,
    longitude: -0.1512,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 60,
    icuBedsAvailable: 4,
    description: "Private hospital serving Adenta and surrounding areas.",
  },
  {
    name: "Frafraha Hospital",
    slug: "frafraha-hospital",
    type: "HOSPITAL",
    phone: "0302525678",
    email: "info@frafrahahospital.com",
    address: "Frafraha",
    city: "Accra",
    districtName: "Adentan Municipal",
    latitude: 5.7234,
    longitude: -0.1389,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 45,
    icuBedsAvailable: 3,
    description: "Private hospital in the Frafraha area.",
  },
  {
    name: "Oyibi Hospital",
    slug: "oyibi-hospital",
    type: "HOSPITAL",
    phone: "0302526789",
    email: "info@oyibihospital.com",
    address: "Oyibi",
    city: "Accra",
    districtName: "Adentan Municipal",
    latitude: 5.7412,
    longitude: -0.1234,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 40,
    icuBedsAvailable: 3,
    description: "Private hospital serving Oyibi and surrounding communities.",
  },
  {
    name: "Kwabenya Hospital",
    slug: "kwabenya-hospital",
    type: "HOSPITAL",
    phone: "0302540123",
    email: "info@kwabenyahospital.com",
    address: "Kwabenya",
    city: "Accra",
    districtName: "Ga East Municipal",
    latitude: 5.6912,
    longitude: -0.2012,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 50,
    icuBedsAvailable: 4,
    description: "Private hospital serving Kwabenya and surrounding areas.",
  },
  {
    name: "Dome Hospital",
    slug: "dome-hospital",
    type: "HOSPITAL",
    phone: "0302541234",
    email: "info@domehospital.com",
    address: "Dome",
    city: "Accra",
    districtName: "Ga East Municipal",
    latitude: 5.6534,
    longitude: -0.2189,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 55,
    icuBedsAvailable: 4,
    description: "Private hospital in the Dome area.",
  },
  {
    name: "Taifa Hospital",
    slug: "taifa-hospital",
    type: "HOSPITAL",
    phone: "0302542345",
    email: "info@taifahospital.com",
    address: "Taifa",
    city: "Accra",
    districtName: "Ga East Municipal",
    latitude: 5.6678,
    longitude: -0.2289,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 45,
    icuBedsAvailable: 3,
    description: "Private hospital serving Taifa and surrounding communities.",
  },
  {
    name: "Pokuase Hospital",
    slug: "pokuase-hospital",
    type: "HOSPITAL",
    phone: "0302960123",
    email: "info@pokuasehospital.com",
    address: "Pokuase",
    city: "Accra",
    districtName: "Ga West Municipal",
    latitude: 5.7123,
    longitude: -0.2912,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 50,
    icuBedsAvailable: 4,
    description: "Private hospital serving Pokuase and surrounding areas.",
  },
  {
    name: "Ofankor Hospital",
    slug: "ofankor-hospital",
    type: "HOSPITAL",
    phone: "0302961234",
    email: "info@ofankorhospital.com",
    address: "Ofankor",
    city: "Accra",
    districtName: "Ga West Municipal",
    latitude: 5.6889,
    longitude: -0.2712,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 45,
    icuBedsAvailable: 3,
    description: "Private hospital in the Ofankor area.",
  },
  {
    name: "Sowutuom Hospital",
    slug: "sowutuom-hospital",
    type: "HOSPITAL",
    phone: "0302962345",
    email: "info@sowutuomhospital.com",
    address: "Sowutuom",
    city: "Accra",
    districtName: "Ga Central Municipal",
    latitude: 5.6234,
    longitude: -0.2612,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 40,
    icuBedsAvailable: 3,
    description: "Private hospital serving Sowutuom and surrounding communities.",
  },
  {
    name: "Abeka Hospital",
    slug: "abeka-hospital",
    type: "HOSPITAL",
    phone: "0302413456",
    email: "info@abekahospital.com",
    address: "Abeka",
    city: "Accra",
    districtName: "Ga Central Municipal",
    latitude: 5.6012,
    longitude: -0.2512,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 50,
    icuBedsAvailable: 4,
    description: "Private hospital in the Abeka area.",
  },
  {
    name: "Odorkor Hospital",
    slug: "odorkor-hospital",
    type: "HOSPITAL",
    phone: "0302310123",
    email: "info@odorkorhospital.com",
    address: "Odorkor",
    city: "Accra",
    districtName: "Ablekuma West Municipal",
    latitude: 5.5612,
    longitude: -0.2712,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 55,
    icuBedsAvailable: 4,
    description: "Private hospital serving Odorkor and surrounding areas.",
  },
  {
    name: "Gbawe Hospital",
    slug: "gbawe-hospital",
    type: "HOSPITAL",
    phone: "0302946234",
    email: "info@gbawehospital.com",
    address: "Gbawe",
    city: "Accra",
    districtName: "Ga South Municipal",
    latitude: 5.5689,
    longitude: -0.3089,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 50,
    icuBedsAvailable: 4,
    description: "Private hospital in the Gbawe area.",
  },
  {
    name: "Mallam Hospital",
    slug: "mallam-hospital",
    type: "HOSPITAL",
    phone: "0302947345",
    email: "info@mallamhospital.com",
    address: "Mallam",
    city: "Accra",
    districtName: "Ga South Municipal",
    latitude: 5.5534,
    longitude: -0.2912,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 45,
    icuBedsAvailable: 3,
    description: "Private hospital serving Mallam and surrounding communities.",
  },
  {
    name: "Bortianor Hospital",
    slug: "bortianor-hospital",
    type: "HOSPITAL",
    phone: "0302948456",
    email: "info@bortianorhospital.com",
    address: "Bortianor",
    city: "Accra",
    districtName: "Ga South Municipal",
    latitude: 5.5234,
    longitude: -0.3512,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 40,
    icuBedsAvailable: 3,
    description: "Private hospital in the Bortianor area.",
  },
  {
    name: "Tema Community 25 Hospital",
    slug: "tema-community-25-hospital",
    type: "HOSPITAL",
    phone: "0303310123",
    email: "info@temac25hospital.com",
    address: "Community 25",
    city: "Tema",
    districtName: "Tema Metropolitan",
    latitude: 5.7012,
    longitude: -0.0412,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 50,
    icuBedsAvailable: 4,
    description: "Private hospital serving Tema Community 25 and surrounding areas.",
  },
  {
    name: "Afienya Hospital",
    slug: "afienya-hospital",
    type: "HOSPITAL",
    phone: "0303320234",
    email: "info@afienyahospital.com",
    address: "Afienya",
    city: "Tema",
    districtName: "Tema Metropolitan",
    latitude: 5.7534,
    longitude: 0.0123,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 40,
    icuBedsAvailable: 3,
    description: "Private hospital in the Afienya area.",
  },
  {
    name: "Kpone Hospital",
    slug: "kpone-hospital",
    type: "HOSPITAL",
    phone: "0303330345",
    email: "info@kponehospital.com",
    address: "Kpone",
    city: "Tema",
    districtName: "Tema Metropolitan",
    latitude: 5.6912,
    longitude: 0.0312,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 45,
    icuBedsAvailable: 3,
    description: "Private hospital serving Kpone and surrounding communities.",
  },
  // New Crystal Health Services - Multiple Locations
  {
    name: "New Crystal Health Services - Ashaiman Main",
    slug: "new-crystal-health-ashaiman-main",
    type: "HOSPITAL",
    phone: "0222307974",
    email: "info@newcrystalhealth.org",
    address: "1st Floor, Post Office Building, Near Main Lorry Station",
    city: "Ashaiman",
    districtName: "Ashaiman Municipal",
    latitude: 5.6945,
    longitude: -0.0298,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 60,
    icuBedsAvailable: 4,
    description: "Main branch of New Crystal Health Services, providing quality affordable healthcare since 2003.",
  },
  {
    name: "New Crystal Health Services - Tema Community 8",
    slug: "new-crystal-health-tema-community-8",
    type: "HOSPITAL",
    phone: "0289103535",
    email: "tema@newcrystalhealth.org",
    address: "Community 8",
    city: "Tema",
    districtName: "Tema Metropolitan",
    latitude: 5.6534,
    longitude: -0.0156,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 45,
    icuBedsAvailable: 3,
    description: "New Crystal Health Services branch in Tema Community 8.",
  },
  {
    name: "New Crystal Health Services - Adjei Kojo",
    slug: "new-crystal-health-adjei-kojo",
    type: "CLINIC",
    phone: "0289103535",
    email: "adjeikojo@newcrystalhealth.org",
    address: "Adjei Kojo",
    city: "Ashaiman",
    districtName: "Ashaiman Municipal",
    latitude: 5.7012,
    longitude: -0.0189,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: false,
    bedCount: 25,
    icuBedsAvailable: 2,
    description: "New Crystal Health Services affiliate clinic in Adjei Kojo.",
  },
  {
    name: "New Crystal Health Services - Michel Camp",
    slug: "new-crystal-health-michel-camp",
    type: "CLINIC",
    phone: "0289103535",
    email: "michelcamp@newcrystalhealth.org",
    address: "Michel Camp",
    city: "Tema",
    districtName: "Tema Metropolitan",
    latitude: 5.7234,
    longitude: -0.0089,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: false,
    bedCount: 20,
    icuBedsAvailable: 1,
    description: "New Crystal Health Services affiliate clinic in Michel Camp.",
  },
  {
    name: "Afenyo Memorial Hospital - New Crystal",
    slug: "afenyo-memorial-hospital-new-crystal",
    type: "HOSPITAL",
    phone: "0289103535",
    email: "afenyo@newcrystalhealth.org",
    address: "Ashaiman",
    city: "Ashaiman",
    districtName: "Ashaiman Municipal",
    latitude: 5.6889,
    longitude: -0.0345,
    nhisAccredited: true,
    emergencyCapable: true,
    ambulanceAvailable: true,
    bedCount: 40,
    icuBedsAvailable: 3,
    description: "Afenyo Memorial Hospital, part of New Crystal Health Services network.",
  },
];

type FacilityType = "HOSPITAL" | "CLINIC" | "PHARMACY" | "DIAGNOSTIC_CENTRE" | "MATERNITY_HOME" | "CHPS_COMPOUND" | "POLYCLINIC" | "HEALTH_CENTRE";

export async function POST() {
  try {
    const session = await auth();

    // Allow seeding without auth for initial setup, or require admin
    // if (session?.user?.role !== "MINISTRY_ADMIN") {
    //   return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    // }

    // Get or create Greater Accra region
    let greaterAccra = await db.region.findFirst({
      where: { name: "Greater Accra" },
    });

    if (!greaterAccra) {
      greaterAccra = await db.region.create({
        data: { name: "Greater Accra", code: "GA" },
      });
    }

    // Create districts
    const districts = [
      "Accra Metropolitan",
      "Tema Metropolitan",
      "Ledzokuku-Krowor",
      "La Dade-Kotopon",
      "Ashaiman Municipal",
      "Ga East Municipal",
      "Ga West Municipal",
      "Ga South Municipal",
      "Ga Central Municipal",
      "Ablekuma West Municipal",
      "Ayawaso North Municipal",
      "La Nkwantanang-Madina Municipal",
      "Adentan Municipal",
      "Ningo-Prampram District",
      "Shai-Osudoku District",
    ];

    const districtMap: Record<string, string> = {};

    for (const districtName of districts) {
      let district = await db.district.findFirst({
        where: { name: districtName, regionId: greaterAccra.id },
      });

      if (!district) {
        district = await db.district.create({
          data: { name: districtName, regionId: greaterAccra.id },
        });
      }
      districtMap[districtName] = district.id;
    }

    // Seed facilities
    let created = 0;
    let skipped = 0;

    for (const facility of FACILITIES) {
      const existing = await db.facility.findFirst({
        where: { slug: facility.slug },
      });

      if (existing) {
        skipped++;
        continue;
      }

      const districtId = districtMap[facility.districtName];
      if (!districtId) continue;

      await db.facility.create({
        data: {
          name: facility.name,
          slug: facility.slug,
          type: facility.type as FacilityType,
          licenseNumber: `GHS-${facility.type.substring(0, 3)}-${Date.now()}-${Math.random().toString(36).substring(7)}`,
          licenseDocumentUrl: "/documents/license-placeholder.pdf",
          phone: facility.phone,
          email: facility.email,
          address: facility.address,
          regionId: greaterAccra.id,
          districtId: districtId,
          latitude: facility.latitude,
          longitude: facility.longitude,
          nhisAccepted: facility.nhisAccredited,
          emergencyCapable: facility.emergencyCapable,
          ambulanceAvailable: facility.ambulanceAvailable,
          bedCount: facility.bedCount,
          icuBedsAvailable: facility.icuBedsAvailable,
          operatingHours: { open: "00:00", close: "23:59", is24Hours: facility.type === "HOSPITAL" },
          description: facility.description,
          status: "APPROVED",
          tier: facility.type === "HOSPITAL" ? "FOUR_STAR" : facility.type === "POLYCLINIC" ? "THREE_STAR" : "TWO_STAR",
          averageRating: 4.0 + Math.random() * 0.9,
          totalReviews: Math.floor(Math.random() * 50) + 10,
        },
      });

      created++;
    }

    return NextResponse.json({
      message: "Facilities seeded successfully",
      created,
      skipped,
      total: FACILITIES.length,
    });
  } catch (error) {
    console.error("Error seeding facilities:", error);
    return NextResponse.json(
      { error: "Failed to seed facilities" },
      { status: 500 }
    );
  }
}
